"use client";

import { getDigest } from "@/lib/api";
import { useApi } from "@/lib/api/useApi";
import { Skeleton } from "../Skeleton";
import { formatPrCount } from "@/lib/app/format";

interface Props {
  visible: boolean;
}

export function DigestView({ visible }: Props) {
  const { data: digest, error, loading } = useApi(
    visible ? "digest:7" : null,
    () => getDigest(7),
    { ttlMs: 5 * 60_000 }, // digest is heavy — cache 5 min
  );

  if (!visible) return null;

  if (error) {
    return (
      <div className="digest-col">
        <p style={{ color: "var(--hot)" }}>Error: {error}</p>
      </div>
    );
  }

  if (loading || !digest) {
    return (
      <div className="digest-col">
        <Skeleton width={140} height={11} style={{ marginBottom: 12 }} />
        <Skeleton width={300} height={32} style={{ marginBottom: 12 }} />
        <Skeleton width={220} height={12} style={{ marginBottom: 28 }} />
        <Skeleton width="100%" height={14} style={{ marginBottom: 8 }} />
        <Skeleton width="92%" height={14} style={{ marginBottom: 8 }} />
        <Skeleton width="84%" height={14} style={{ marginBottom: 28 }} />
        <Skeleton width={140} height={16} style={{ marginBottom: 12 }} />
        <Skeleton width="100%" height={12} style={{ marginBottom: 6 }} />
        <Skeleton width="86%" height={12} style={{ marginBottom: 6 }} />
        <Skeleton width="74%" height={12} />
      </div>
    );
  }

  const start = new Date(digest.period_start);
  const end = new Date(digest.period_end);
  const monthDay = (d: Date) =>
    d.toLocaleDateString("en-US", { month: "short", day: "numeric" });

  return (
    <div className="digest-col">
      <div className="label-tight mb-3">Engineering digest</div>
      <h1 className="display">
        {monthDay(start)} <span className="italic-serif">— {monthDay(end)}</span>
      </h1>
      <p className="text-[13.5px]" style={{ color: "var(--ink2)", marginTop: 4 }}>
        Generated by DyPol · {new Date().toLocaleString()}
      </p>

      <hr className="my-7" style={{ borderColor: "var(--hairline)" }} />

      <h2>What shipped</h2>
      <p>
        <span className="num text-[14px]">{digest.prs_merged} PRs merged</span> ·{" "}
        <span className="num text-[14px]">{digest.prs_opened} opened</span> ·{" "}
        <span className="num text-[14px]">{digest.commits} commits</span> from top contributors.
      </p>

      <h2>Who's killing it</h2>
      {digest.top_contributors.length === 0 ? (
        <p className="text-ink2">No contributor activity in this period.</p>
      ) : (
        <ul className="space-y-2 mt-2">
          {digest.top_contributors.map((c, i) => (
            <li key={c.login} className="flex items-center gap-3">
              <span className="num text-[12px]" style={{ color: "var(--ink3)", width: 24 }}>
                {String(i + 1).padStart(2, "0")}
              </span>
              {c.avatar_url && (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={c.avatar_url}
                  alt={c.login}
                  width={24}
                  height={24}
                  style={{ borderRadius: "50%" }}
                />
              )}
              <strong>{c.name ?? c.login}</strong>
              <span style={{ color: "var(--ink2)" }}>
                · {c.commits} commits, {c.prs_merged} PRs merged
              </span>
            </li>
          ))}
        </ul>
      )}

      <h2>Active repos</h2>
      <ul className="space-y-1.5 mt-2">
        {digest.top_repos.map((r) => (
          <li key={r.full_name}>
            <span className={`dot ${r.status}`} style={{ marginRight: 8 }} />
            <span className="mono text-[13px]">{r.name}</span>
            <span style={{ color: "var(--ink2)" }}> · {formatPrCount(r)} open PRs</span>
            {r.summary && (
              <span style={{ color: "var(--ink3)" }}> — {r.summary}</span>
            )}
          </li>
        ))}
      </ul>

      <hr className="my-10" style={{ borderColor: "var(--hairline)" }} />
      <p className="text-[13px]" style={{ color: "var(--ink3)" }}>
        DyPol only counts pushed work. Counts come live from your GitHub installation.
      </p>
    </div>
  );
}
